spring:
  application:
    name: todo-user
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
  mvc:
    problemdetails:
      enabled: false
application:
  auth:
    jwt:
      public-key:
      private-key:
  logging:
    request-id-header: "X-REQUEST-ID"
    request-id-key: "request_id"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      hikaricp: true
#logging:
#  structured:
#    format:
#      console: logstash
springdoc:
  api-docs:
    version: openapi_3_0
  cache:
    disabled: true
  use-management-port: true