spring:
  application:
    name: todo-user
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
application:
  auth:
    jwt:
      public-key:
      private-key:

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      hikaricp: true
