services:
  todo-user:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/todo-user"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      LOGGING_STRUCTURED_FORMAT_CONSOLE: logstash
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo-user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: